on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  check-package:
    runs-on: ubuntu-latest
    name: "check package"
    steps:
      - name: testdeploy
        run: |
          git clone https://oauth2:$GITHUB_TOKEN@github.com/thierryo/abvtest check
          cd check
          git config user.name "Checklist bot"
          git config user.email "checklist@inbo.be"
          git config advice.detachedHead false
          git checkout $GITHUB_SHA
          cp index.html ../index.html
          if [ -z  "$(git branch -r | grep origin/gh-pages)" ]; then
            git checkout --orphan gh-pages
            git rm -rf --quiet .
            git commit --allow-empty -m "Initializing gh-pages branch"
          else
            git checkout -b gh-pages
            git rm -rf --quiet .
            rm -R *
          fi
          cp ../index.html index.html
          git add index.html
          git commit --amend -m "Automated update of gh-pages website"
          git push --force --set-upstream origin gh-pages
